### ISSUE TITLE
Lincense - MIT?

### ISSUE THREAD

**Issue by maxwondercorn** [zmink-pxc/react-axl#31]
@zmink-pxc 

I see that you have assigned the MIT license in `package.json` but the repo doesn't have a corresponding license file.  I'm interested in potentially using your components for a plcNext project but can not use them without the MIT license.

The easiest way to add a license file after creation is using GitHub's `Add a file` function [docs here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository)

**Comment by zmink-pxc** [comment]
Hi Mr. Wondercorn, thanks for your interest!  I have added a license file in #32.  I have a bit collection created for this project here: [@bit](https://bit.dev/zmink).  The axiobus component may be of most interest: [axiobus](https://bit.dev/zmink/axioline/axiobus)
